apiVersion: v1
name: goldpinger
appVersion: "4.0.0"
version: 4.0.0
description: Goldpinger is a tool to help debug, troubleshoot and visualize network connectivity and slowness issues.
home: https://github.com/bloomberg/goldpinger
sources:
  - https://github.com/bloomberg/goldpinger
  - https://github.com/eumel8/goldpinger
